server:
  port: 8181
Spring:
  application:
    name: college
  datasource:
    name: test
    url:  jdbc:mysql://localhost:3306/ravionics
    username: root
    password: root
    driver:
      class-name: com.mysql.cj.jdbc.Driver
  jpa:

    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update